version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "urbansportsclub/sre"
    reviewers:
      - "urbansportsclub/sre"
    open-pull-requests-limit: 10
