---
Name: Auto-merge dependabot PR's

on: 
  workflow_call:
    secrets:
      github-token:
        required: true

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    name: Dependabot auto-merge
    runs-on: [self-hosted]
    timeout-minutes: 15
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.6.0
      with:
        github-token: "${{ secrets.github-token }}"

    - name: Approve a PR
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.github-token }}

    - name: Enable auto-merge for Dependabot PRs
      if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.github-token }}
