---
name: Publish TechDocs

on:
  push:
    branches: [ dev/DX-537 ]

jobs:
  publish-techdocs-site:
    uses: urbansportsclub/usc-reusable-workflows/.github/workflows/generate-techdocs.yaml@main
    with:
      BACKSTAGE_ENTITY_NAMESPACE: "default"
      BACKSTAGE_ENTITY_KIND: "Component"
      BACKSTAGE_ENTITY_NAME: "usc-reusable-workflows"