name: Publish TechDocs Site

on:
  workflow_call:
    inputs:
      TECHDOCS_GCS_BUCKET_NAME:
        required: false
        type: string
        description: "GCS Bucket Name for TechDocs" # should we make it configurable or generate docs to the same bucket always
        default: "urbansportsclub-dev-backstage-techdocs" # for test, I'll use dev
      BACKSTAGE_ENTITY_NAMESPACE:
        required: false
        type: string
        description: "Backstage Entity Namespace"
        default: 'default'
      BACKSTAGE_ENTITY_KIND:
        required: true
        type: string
        description: "Backstage Entity Kind"
        default: 'Component'
      BACKSTAGE_ENTITY_NAME:
        required: true
        type: string
        description: "Backstage Entity Name"

jobs:
  publish-techdocs-site:
    runs-on: [self-hosted, deploydevelopment]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Note: We recommend Python version 3.11 or higher.
          cache: 'pip' # caching pip dependencies
      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: |
          techdocs-cli publish --publisher-type googleGcs \
          --storage-name ${{ inputs.TECHDOCS_GCS_BUCKET_NAME }} \
          --entity ${{ inputs.BACKSTAGE_ENTITY_NAMESPACE }}/${{ inputs.BACKSTAGE_ENTITY_KIND }}/${{ inputs.BACKSTAGE_ENTITY_NAME }}
