name: Publish TechDocs Site

on:
  workflow_call:
    inputs:
      BACKSTAGE_ENTITY_NAMESPACE:
        required: false
        type: string
        description: "Backstage Entity Namespace"
        default: 'default'
      BACKSTAGE_ENTITY_KIND:
        required: false
        type: string
        description: "Backstage Entity Kind"
        default: 'Component'
      BACKSTAGE_ENTITY_NAME:
        required: true
        type: string
        description: "Backstage Entity Name"

jobs:
  publish-techdocs-site:
    runs-on: [self-hosted, deploydevelopment] # It needs to run on services to have access to the bucket

    env:
      GCS_BUCKET_NAME: urbansportsclub-dev-backstage-techdocs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install techdocs-cli
        run: npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: |
          techdocs-cli publish --publisher-type googleGcs \
          --storage-name ${{ env.GCS_BUCKET_NAME }} \
          --entity ${{ inputs.BACKSTAGE_ENTITY_NAMESPACE }}/${{ inputs.BACKSTAGE_ENTITY_KIND }}/${{ inputs.BACKSTAGE_ENTITY_NAME }}
