name: Rollback Helm Deployment

on:
  workflow_call:
    inputs:
      gke_zone:
        required: false
        type: string
        default: "europe-west3"
      gke_cluster:
        required: true
        type: string
        description: "Kubernetes Cluster Name" 
        default: "internal"
      chart_name:
        required: true
        type: string
        description: "Helm chart name." 
        default: "usc-test-helm"
      version:
        required: false
        type: string
        description: "Revision (version) number. If this argument is omitted, it will rollback to the previous release." 
        default: 0
      namespace:
        required: true
        type: string
        description: "Kubernetes namespace" 
        default: "default"
      project_id:
        required: false
        type: string
        description: "Project id for gcloud (whenever you deploy to)."
        default: "urbansportsclub-dev"
      runner:
        required: false
        type: string
        description: "Runner type [ deploy, deploylive ] (Default deploy)."
        default: "deploy"
        

jobs:
  rollback-helm-deployment:
    name: Helm rollback kubernetes deployment
    runs-on: [self-hosted, "${{ inputs.runner }}"]
    steps:
      - name: Set up K8s config
        run: |-
          gcloud container clusters get-credentials ${{ inputs.gke_cluster }} --region ${{ inputs.gke_zone }} --project ${{ inputs.project_id }}

      - name: Helm Rollback
        run: |-
          helm rollback ${{ inputs.chart_name }} --namespace ${{ inputs.namespace }} ${{ inputs.version }}  

