---
name: Lint Code Base

on:
  workflow_call:
    secrets:
      github-token:
        required: true
    inputs:
      branch:
        required: false
        type: string
        default: "main"
      enable_jscpd:
        required: false
        type: boolean
        default: true
      enable_go:
        required: false
        type: boolean
        default: false
      validate_all_codebase:
        required: false
        type: boolean
        default: false
      enable_kubeform:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: [self-hosted, nonroot]
    name: Lint Code Base

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Lint Code Base
        uses: docker://github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          DEFAULT_BRANCH: ${{ inputs.branch }}
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
          VALIDATE_GO: false
          KUBERNETES_KUBECONFORM_OPTIONS: "-ignore-missing-schemas"
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
          VALIDATE_JSCPD: ${{ inputs.enable_jscpd }}
          VALIDATE_KUBERNETES_KUBECONFORM: ${{ inputs.enable_kubeform }}
          VALIDATE_KUBERNETES_KUBEVAL: ${{ inputs.enable_kubeform }}

  golang:
    if: inputs.enable_go == true
    name: Lint Golang Files
    runs-on: [self-hosted, nonroot]
    timeout-minutes: 15

    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure private repo
        run: git config --global url."https://${{ secrets.github-token }}:x-oauth-basic@github.com/urbansportsclub".insteadOf "https://github.com/urbansportsclub"

      - name: Lint Code Base
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          args: -c ./.github/linters/.golangci.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
