---
name: Lint Code Base

on:
  workflow_call:
    secrets:
      github-token:
        required: true
    inputs:
      branch:
        required: false
        type: string
        default: "main"

jobs:
  build:
    runs-on: [self-hosted, nonroot]
    name: Lint Code Base

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Lint Code Base
        uses: docker://github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          DEFAULT_BRANCH: ${{ inputs.branch }}
          VALIDATE_ALL_CODEBASE: false
          KUBERNETES_KUBECONFORM_OPTIONS: "-ignore-missing-schemas"
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
