name: Lint Code Base  

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: "main"
      language:
        required: true
        type: string
        default: ""
        description: "Language to be linted"


jobs:
  build:
    runs-on: [self-hosted,nonroot]
    name: Lint Code Base

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base #
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: $BRANCH
          VALIDATE_$LANGUAGE: true
