name: Linting and Formatting
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: Working directory path.
        default: "."
        required: false
        type: string
    secrets:
      GH_PACKAGES_TOKEN:
        required: true
jobs:
  lint-and-format:
    name: ESLint and Prettier formatting
    runs-on: [self-hosted, nonroot]
    env:
      NODE_CMD_MODE: ""
      LOCK_FILE: ""

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup NODE_CMD_MODE/LOCK_FILE values
        run: |
          if [ -f "${{ inputs.WORKING_DIRECTORY }}/yarn.lock" ]; then
            echo "NODE_CMD_MODE=yarn" >> $GITHUB_ENV
            echo "LOCK_FILE=${{ inputs.WORKING_DIRECTORY }}/yarn.lock" >> $GITHUB_ENV
          elif [ -f "${{ inputs.WORKING_DIRECTORY }}/pnpm-lock.yaml" ]; then
            echo "NODE_CMD_MODE=pnpm" >> $GITHUB_ENV
            echo "LOCK_FILE=${{ inputs.WORKING_DIRECTORY }}/pnpm-lock.yaml" >> $GITHUB_ENV
          else
            echo "NODE_CMD_MODE=npm" >> $GITHUB_ENV
            echo "LOCK_FILE=${{ inputs.WORKING_DIRECTORY }}/package-lock.json" >> $GITHUB_ENV
          fi

      # Restore NPM cache
      - name: Restore node_modules cache
        uses: actions/cache@v4
        id: node-cache
        with:
          path: ${{ inputs.WORKING_DIRECTORY }}/node_modules
          key: node-cache-${{ runner.os }}-${{ hashFiles(env.LOCK_FILE) }}

      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.WORKING_DIRECTORY }}/.nvmrc
          registry-url: "https://npm.pkg.github.com"

      - if: ${{ env.NODE_CMD_MODE == 'yarn' }}
        name: Conditional Yarn install for runner if used
        run:  npm -g install yarn

      - name: Install Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          INSTALL_ARGS: ${{ env.NODE_CMD_MODE == 'npm' && 'ci' || env.NODE_CMD_MODE == 'yarn' && '--frozen-lockfile' || 'install' }}
        run: ${{ format('{0} {1}', env.NODE_CMD_MODE, env.INSTALL_ARGS) }}

      # Run Linter
      - name: ESLint
        run: ${{ ((env.NODE_CMD_MODE == 'npm') && 'npm run') || 'yarn' }} lint
      
      # Run Formatter
      - name: Prettier
        run: ${{ ((env.NODE_CMD_MODE == 'npm') && 'npm run') || 'yarn' }} format 
