name: Playwright E2E Tests
on:
  push:
    branches: [main, master]
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        default: "."
        required: false
    secrets:
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  e2e_tests:
    name: Playwright E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Set Node version (requires .nvmrc file in the root of repository)
      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.WORKING_DIRECTORY }}/.nvmrc
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
