name: Playwright E2E Tests
on:
  push:
    branches: [main, master]
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        default: "."
        required: false
      PACKAGE_MANAGER:
        description: Package manager to install dependencies with (`npm` or `yarn`).
        default: "npm"
        required: false
        type: string
    secrets:
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  e2e_tests:
    name: Playwright E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NODE_CMD_MODE: ""
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup NODE_CMD_MODE env var
        run: |
          if [ "${{ inputs.PACKAGE_MANAGER }}" == 'npm' ] && { [ -f "${{ inputs.WORKING_DIRECTORY }}/package-lock.json" ]; }; then
            echo "NODE_CMD_MODE=npm" >> $GITHUB_ENV
          elif [ "${{ inputs.PACKAGE_MANAGER }}" == 'yarn' ] && [ -f "${{ inputs.WORKING_DIRECTORY }}/yarn.lock" ]; then
            echo "NODE_CMD_MODE=yarn" >> $GITHUB_ENV
          else
            echo "Unknown package manager usage OR no lock files found within working dir"
          fi

      # Set Node version (requires .nvmrc file in the root of repository)
      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.WORKING_DIRECTORY }}/.nvmrc
          registry-url: "https://npm.pkg.github.com"
          cache: ${{ env.NODE_CMD_MODE }}

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          INSTALL_ARGS: ${{ env.NODE_CMD_MODE == 'npm' && 'ci' || env.NODE_CMD_MODE == 'yarn' && '--frozen-lockfile' || 'install' }}
        run: ${{ format('{0} {1}', inputs.PACKAGE_MANAGER, env.INSTALL_ARGS) }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
