---
# This workflow is used to publish the TechDocs site for the USC reusable workflows repository.
# This is not a reusable workflow.
name: Publish TechDocs

on:
  push:
    branches: [ main ]

jobs:
  publish-techdocs-site:
    uses: urbansportsclub/usc-reusable-workflows/.github/workflows/generate-techdocs.yaml@main
    with:
      BACKSTAGE_ENTITY_NAMESPACE: "default"
      BACKSTAGE_ENTITY_KIND: "Component"
      BACKSTAGE_ENTITY_NAME: "usc-reusable-workflows"
      