name: Terraform Apply
on:
  workflow_call:
    inputs:
      terraform_path:
        required: false
        type: string
        description: "Path for Terraform files"
        default: "terraform/"
      tf_args:
        required: false
        type: string
        description: "Additional Terraform variables"
        default: ""

jobs:
  terraform:
    name: Apply
    runs-on: [terraform]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change directory to the Terraform path
        run: cd ${{ inputs.terraform_path }}

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve -input=false ${{ inputs.tf_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
