name: Unit Testing
on:
  workflow_call:
    inputs:
      REPO_NAME:
        required: true
        type: string
      USE_CODECOV:
        required: false
        type: boolean
        default: false
      UPLOAD_ARTIFACTS:
        required: false
        type: boolean
        default: false
      WORKING_DIRECTORY:
        type: string
        default: "."
        required: false
    secrets:
      GH_PACKAGES_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: false

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: [self-hosted, deploy]
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Restore `node_modules`
        uses: actions/cache@v4
        id: node-cache
        with:
          path: ./node_modules
          key: node-cache-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: List Files
        run: ls -la

      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.WORKING_DIRECTORY }}/.nvmrc
          registry-url: "https://npm.pkg.github.com"

      - name: Clean Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Run Unit Test Script
        run: npm run test

      - name: Codecov Coverage Report
        if: ${{ inputs.USE_CODECOV }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: Jest
          name: ${{ inputs.REPO_NAME }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload Code Coverage Artifacts to `test-artifacts`
        uses: actions/upload-artifact@v4
        if: ${{ inputs.UPLOAD_ARTIFACTS }}
        with:
          name: test-artifacts
          path: ${{ inputs.WORKING_DIRECTORY }}/coverage
